### ISSUE TITLE
on 128x32 oled driven by ssd1306, the font of 'show string' is too narrow

### ISSUE THREAD

**Issue by sonictl** [lbaitemple/rpi-pico-ssd1306#1]
on 128x32 oled driven by ssd1306, the font of 'show string' is too narrow. 128x64 is ok.

**Comment by lbaitemple** [comment]
I will verify. The code is at main.ts line 39. You can specify a different value for displayHeight.
 let displayHeight = 64 / 8

**Comment by lbaitemple** [comment]
> on 128x32 oled driven by ssd1306, the font of 'show string' is too narrow. 128x64 is ok.

Can you test the code again? I updated the code so it should work on a 128x32 oled ssd1306 now.
